### ISSUE TITLE
Problems with 'Redirecting you back to the application' and minego.net

### ISSUE THREAD

**Issue by bobcanthelpyou** [minego/macaw-enyo#66]
I installed the latest Macaw version from GitHub to a Firefox OS 2.0 device. I could authorize the App with Twitter but the redirect doesn't work.

WebIDE shows no response from the following GET request and got stuck there:
````
GET https://minego.net/macawtwitter/
````
It is also not possible to access this site, ping to the website results in 100% packet loss

**Comment by minego** [comment]
I had some network issues last night. They should be resolved now (or in 
the next few minutes).

**Comment by bobcanthelpyou** [comment]
Thx it is working now :)
