### ISSUE TITLE
Non standard license make it impossible to contribute

### ISSUE THREAD

**Issue by hfiguiere** [minego/macaw-enyo#70]
The use of a non standard license, and unclear, makes it impossible to contribute without having a law degree to understand it. Notable the "non commercial" clause is just too vague.

Please switch to a known license so at least things are clear.

**Comment by mozfreddyb** [comment]
I'd be happy to contribute, as well, if this was resolved.
FWIW, Macaw is one the more popular twitter clients for Firefox OS.

**Comment by minego** [comment]
This is the first anyone has brought this up. I'd be happy to switch the
license. I'll do some research and change this.

The intent of that clause was simply that I don't want someone to put the
app in an app store and sell it without contributing anything.

**Comment by mozfreddyb** [comment]
Thanks for taking this into consideration! We certainly don't want to push anything

This website helped me in the past: http://choosealicense.com/

**Comment by minego** [comment]
I've just pushed a change that switches the license to the MPL 2.0. 
Please let me know if you still have concerns. I don't want a license 
that discourages contributions.

Micah

**Comment by minego** [comment]
The license has been switched to the MPL 2.0.

**Comment by hfiguiere** [comment]
(as the OP) MPL is good for me. Thanks !

**Comment by mozfreddyb** [comment]
Thanks!
